# Configuration file for TravisCI
os: linux
dist: xenial
language: generic
notifications:
  email: false

# Only build pushes to the master branch and tags. This avoids the double
# builds than happen when working on a branch instead of a fork.
branches:
  only:
    - master
    # Regex to build tagged commits with version numbers
    - /\d+\.\d+(\.\d+)?(\S*)?$/

addons:
  apt:
    packages:
      - hub

env:
  global:
      # Encrypted variables
      - secure: "NI37cpQL9T95wpRK9UAhfSkvrK5GtFow5uAyS3G3sSb7uYelAd/rfqXOyBoHakuHFxzYUpDOl2RjYdaM09bPU73xaalj3KUKU5JALFMN+YW9BoqzDACvqR+4y2pbmZuJrYQTyWvhUGDnUcJyNC1aLlddt/P082Vvkx5HBSf9PXJbNuSiaIk7Pth3QZ+zCDSbjLS2cryQTT2PFmx/D/wYimp8yYBximbqkyicPZLr3mFgMyi/SN3ltXr5H/mIK+VTWjuvvpJi4VF7j2i5olqlJ7BlUzMYlGVKouqQjJo6a6Q5uJLfj0DIzMHVunhJU/3Igu0yT8AclbCBG7IrJ5/zasCE1t+5bHpWSRbX52fU46Vj+tSh4RtErZO6jyYBtSOSjLH7Keltp5yxTLGAyDTD3Jn/x+riPLiFen953g3d9o7fOcpS015PK3Qmv/DTfcBfCbstU1soSQNAhlgICWk1MbwbWDrgz46A3BM7QU0DRmSZ9Rri0FWdtn+67zZ99HrzPb2bORAhBnQ4CtRQnwTO4hv3TA+Kt3UW+mAG6AQ3YQ5N0BZsMztMnbMeeFCOBCSAxkq5wDYjkQtycwn97ftFW5JMDsidejiuaSc4mxJSuAoTH5qaEv6xDidD4kxmpw7FKJWQJ4ikvKB9mQcb/1ZG+qx7RufvH3RbfLdS2+Y4Lgc="
      - TRACKED_FILES="CONTRIBUTING.md MAINTENANCE.md CODE_OF_CONDUCT.md"
      - REPOSITORIES="fatiando/verde fatiando/harmonica fatiando/pooch fatiando/rockhound"

script:
  - ./ci/make-prs.sh
