# Configuration file for TravisCI
os: linux
dist: xenial
language: generic
notifications:
  email: false

branches:
  only:
    - master

env:
  global:
      - secure: "L5JYkz6PEsL3vZWdl4l6+BrjJqJgSSwkk+3V8NHpT9Hs7ME7puYI+88Fm0U+fWDCpFDPEGKygob/e4DvhpwfOQaSH7y90hx0/Gdfnj02gCWB9C51JE49ZRcbgbOwo5zLlxEZQrHo+9Urn+EGzfuz0eS2di7W9GulZBf3XNf7U8wLQC7zfrSNa2GRTUVbGHRAcV8jR3b5eiro415GqOsgn7/k+J0HQvLiWqb10PFxpwnAG2t88vvRXWFrXf1BJfYIT3mASagc2Dh8fLmoEkPxmm95O9CPaOaL5l7s5OEcF845Q9QyK6AEtzm1dncAQETZIf2C1+aMXBADIb3gDFDE57zsBPXqxkS4QfWgDQl/nNNxbhvlOJUA/rta5sEzbXBw0pCkvtELCyCX0TELt5YpUGrMJ6DHZNHegyz4hLX6R2fbgZI7dZuzuaMIt4C0PcSiepVEfwLrHTpJsVIhqHB4AJUu/zy1OO4Ag3Cy1n8kNu1ld4kkHZ601v0SxwpEheN8LAW4pgktlWbxSbSE1GIVM8NQ1816pLYfCyp1/06bTdeAW6H1JnfxT/Ih6kphretp+sMlx2UXGKESAuJ54GlCkNmCvQPz4qVhzMzfqtGyiDn1wKyCUftklV1Y8iCDsg42orKAf3dHNcJNZbt0vz7fc7KGIiF2OT4E9wSXgq35tu0="
      - TRACKED_FILES="CONTRIBUTING.md MAINTENANCE.md CODE_OF_CONDUCT.md"
      - REPOSITORIES="verde harmonica pooch rockhound"

install:
  - sudo add-apt-repository ppa:cpick/hub -y
  - sudo apt-get update -q
  - sudo apt-get install hub -y

script:
  - ./ci/make-prs.sh
